import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { Toaster } from "sonner"
import { Card, CardContent } from "@/app/_components/ui/card"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="dark flex min-h-full flex-col">
        {children}
        <Toaster />
        <footer className="border-border border-t py-4">
          <div className="container mx-auto flex items-center justify-center">
            <p className="text-muted-foreground text-sm">
              © 2026{" "}
              <span className="font-medium text-[#C3F32C]">RéguaMaximum</span>.
              Todos os direitos reservados.
            </p>
          </div>
        </footer>
      </body>
    </html>
  )
}
