import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { Toaster } from "sonner"
import Fotter from "./_components/ui/footer"
import Header from "./_components/header"
import AuthProvider from "./_providers/auth"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="dark flex min-h-full flex-col">
        {/* <Header /> */}
        <AuthProvider>
          <div className="flex flex-col h-full">
            <div className="flex-1">{children}</div>
            <Fotter />
          </div>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  )
}
