
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import AuthProvider from "./_providers/auth"
import { ThemeProvider } from "./_components/theme-provider"
import { ToasterWithTheme } from "./_components/toaster-with-theme"
import Footer from "@/app/_components/ui/footer"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full custom-scrollbar overflow-y-auto">
        <ThemeProvider>
          <AuthProvider>{children}</AuthProvider>
          <ToasterWithTheme />
          <Footer></Footer>
        </ThemeProvider>
      </body>
    </html>
  )
}

